config/routes.rb
Chatroom::Application.routes.draw do
  get "about" => "pages#about", as: "about"
  get "contact" => "pages#contact", as: "contact"
  devise_for :users
  resources :profiles, only: [:show]
  resources :languages do
      get "followers" => "languages#languagefollowers", as: "languages_followers"
    resources :hangouts do
      resources :posts, only: [:create]
      get 'tags/:tag', to: 'hangouts#show', as: "tag"
    end
  end

  resources :rsvps, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  resources :languagefollows, only: [:create, :destroy]

  root 'pages#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user, dependent: :destroy
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_profile, only: [:show]
    before_action :set_rsvps, only: [:show]
	before_action :set_user, only: [:show]
    before_action :authenticate_user!

	def show

        if current_user == @user
            @user_hangouts = Hangout.where(user_id: @user.id).order("start_time asc")

            if params[:live].present?
                @user_hangouts = @user_hangouts.live 
            elsif params[:active].present?
                @user_hangouts = @user_hangouts.active
            elsif params[:archived].present?
                @user_hangouts = @user_hangouts.archived
            elsif params[:joined].present?
                @user_hangouts = Hangout.joined
            end
        else
            @user_hangouts = Hangout.where(["user_id= ? and private = ? and end_time > ?", @user.id, false, Time.now])
        end
        
		@user_rsvps = Rsvp.where(user_id: @user.id)
        @followers = @user.followers_by_type('User')
        @following = @user.following_user
        @following_languages = @user.following_by_type('Language')

        @following_hangouts = Hangout.where(user_id: @following).where(["end_time > ?", Time.now])        
	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
    	@user = @profile.user
    end

    def set_profile
      @profile = Profile.find(params[:profile_id]) rescue Profile.find(params[:id])
    end

    def set_rsvps
        @rsvps = Rsvp.where(user_id: @profile.user)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_followers.html.erb
<div class="followers text-center row">
	<div class="large-12">
		<h4><%= @profile.user.username + "'s followers" %></h4>
	<% if @user.followers_by_type_count('User') == 0 %>
		<% if current_user == @profile.user %>
		<p>You don't have any followers yet. Start a chat and make some friends :)</p>
		<% else %>
		<p>Why not be this person's first follower? <%= link_to 'Follow', follows_path(id: @profile), method: :post, id:"follow-submit", class: "button small success round tiny" %></p>
		<% end %>
	<% else %>
	<table>
		<tbody>
			<% @followers.each do |follower| %>
				<tr>
					<td><%= link_to( image_tag(follower.avatar.url(:thumb)), profile_path(follower.profile)) %></td>
					<td><%= link_to follower.username, profile_path(follower.profile) %><br>
						<%= truncate(follower.bio, :length => 60) %></td>
					<td>
							<%= render partial: 'follows/user_follow', locals: { user: follower } %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<% end %>
</div>
</div>

app/views/profiles/_following.html.erb
<div class="followers text-center row">
	<div class="large-12">
		<h4><%= @profile.user.username + ' follows' %></h4>
		<% if @user.following_by_type_count('User') == 0 %>
		<% if current_user == @profile.user %>
		<p>You aren't following anyone yet. Don't be shy! :)</p>
		<% else %>
		<p>This person isn't following anyone yet.</p>
		<% end %>
	<% else %>
	<table>
		<tbody>
			<% @following.each do |follower| %>
				<tr>
					<td><%= link_to( image_tag(follower.avatar.url(:thumb)), profile_path(follower.profile)) %></td>
					<td><%= link_to follower.username, profile_path(follower.profile) %><br>
						<%= truncate(follower.bio, :length => 60) %></td>
					<td>
							<%= render partial: 'follows/user_follow', locals: { user: follower } %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<% end %>
</div>
</div>

app/views/profiles/_following_chats_tab.html.erb
<!-- Following Hangouts -->
		  <div class="content" id="followingChats">
			    <div class="row">
				  <div id="pins" class="transitions-enabled small-12 medium-10 large-6">
				  	<% unless @following_hangouts.present? %>
				  		
				  		<div class="text-center">
				  			<% if current_user == @profile.user %>
				  			<h3>Sorry. Couldn't find anything.</h3>
				  			<p>Looks like none of the people you follow have any active chats right now.</p>
				  			<% else %>
				  			<h3>Sorry. Couldn't find anything.</h3>
				  			<p>Looks like none of the people <%= @profile.user.username %> follows have any active chats right now.</p>
				  			<% end %>
				  		</div>
				  		
			  		<% else %>
				  	<% @following_hangouts.each do |hangout| %>
						<% unless @user != current_user && hangout.private%>
						<%= render partial: 'profiles/rsvped_hangouts', locals: {language: hangout.language.id, hangout: hangout } %>
						<% end %>
				    <% end %>
				    <% end %>
					</div>
				</div>
			</div>

app/views/profiles/_language_followers.html.erb
	<div class="followers text-center row">
	<div class="large-12">
		<h4>People Following <%= language.name %></h4>
	      <% if language.followers_by_type_count('User') == 0 %>
		  <p>Cool! You can be this language's first follower! <%= link_to 'Follow', follows_path(id: @profile), method: :post, id:"follow-submit", class: "button small success round tiny" %></p>
			<% else %>
			<table>
				<tbody>
				  <% language.user_followers.each do |user| %>
				    <% unless current_user == user %>
				      <tr>
						<td><%= link_to( image_tag(user.avatar.url(:thumb)), profile_path(user.profile)) %></td>
						<td>
							<%= link_to user.username, profile_path(user.profile), class: "follower-name" %>
							<p class="follower-bio"><%= truncate(user.bio, :length => 60) %></p>
						</td>
						<td>
							<%= render partial: 'follows/user_follow', locals: { user: user } %>
					    </td>
					  </tr>
					<% end %>
				  <% end %>
				  </tbody>
			</table>
		  <% end %>
    	<a class="close-reveal-modal">&#215;</a>
	</div>
   </div>

app/views/profiles/_my_chats_tab.html.erb
<!-- My Hangouts -->
		  <div class="content" id="myChats">
		  	<% unless current_user != @profile.user %>
		  	<div class="text-center row">
		  		<div style="padding: 2em;" class="center big-bottom large-12 columns">
		  			<% unless @following_languages.present? %>
						<h3>Create conversations from your profile: <%= link_to languages_path, id: "End", class: "button success" do %>
						Follow a language to start <i class="fi-arrow-right"></i>
						<% end %>
					<% else %>
		  			<h3>Schedule a New Conversation for 
		  			<button href="#" data-dropdown="languages" aria-controls="drop1" aria-expanded="false" class="button dropdown success round">Select Language</button><br>
					<ul id="languages" data-dropdown-content class="f-dropdown" aria-hidden="true" tabindex="-1">
						<% @following_languages.each do |language| %>
					  <li><%= link_to language.name, new_language_hangout_path(language) %></li>
					  <% end %>
					  <% end %>
					</ul></h3>
		  		</div>
		  		<button href="#" data-dropdown="sort" aria-controls="drop1" aria-expanded="false" class="button dropdown tiny round">Sort</button><br>
					<ul id="sort" data-dropdown-content class="f-dropdown" aria-hidden="true" tabindex="-1">
					  <li><%= link_to 'Live', profile_path(@user.profile, :live => true)%></li>
					  <li><%= link_to 'Active', profile_path(@user.profile, :controller => "hangouts", :active=> true) %></li>
					  <li><%= link_to 'Joined', profile_path(@user.profile, :joined => true)%></li>
					  <li><%= link_to 'Old', profile_path(@user.profile, :archived => true) %></li>
					</ul>
		  	</div>
		  	<% end %>

		  	<% unless @user_hangouts.present? %>
		  		<div class="text-center">
			  			<% if current_user == @profile.user %>
			  			<h3>You don't have any chats.</h3>
			  			<p>Start by adding one with the button above.</p>
			  			<% else %>
			  			<h3><%=@profile.user.username %> doesn't have any active or public chats right now.</h3>
						<% end %>
			  		</div>
		  	<% else %>
		    <div class="row">
			  <div id="pins" class="transitions-enabled small-12 medium-10 large-6">
				<%= render partial: 'hangouts/hangout_pins', locals: { hangouts: @user_hangouts } %>
				</div>
			</div>
			<% end %>
		</div>

app/views/profiles/_public_tabs.html.erb
<ul class="tabs" data-options="deep_linking:true" data-tab role="tablist">
	  <li class="tab-title active" role="presentational" ><a href="#panel2-1" role="tab" tabindex="0" aria-selected="true" controls="panel2-2">Upcoming Chats</a></li>
	  <li class="tab-title" role="presentational"><a href="#panel2-2" role="tab" tabindex="0" aria-selected="false" controls="panel2-3">Following Chats</a></li>
	</ul>
	<div class="tabs-content">
	  
	  <section role="tabpanel" aria-hidden="true" class="content" id="panel2-1">
	    <%= render 'profiles/rsvped_tab' %>
	  </section>
	  <section role="tabpanel" aria-hidden="true" class="content" id="panel2-2">
	    <%= render 'profiles/following_chats_tab' %>
	  </section>
	</div>

<ul class="tabs" data-tab role="tablist">
  <li class="tab-title active" role="presentational" ><a href="#panel2-1" role="tab" tabindex="0" aria-selected="true" controls="panel2-1">Tab 1</a></li>
  <li class="tab-title" role="presentational" ><a href="#panel2-2" role="tab" tabindex="0"aria-selected="false" controls="panel2-2">Tab 2</a></li>
  <li class="tab-title" role="presentational"><a href="#panel2-3" role="tab" tabindex="0" aria-selected="false" controls="panel2-3">Tab 3</a></li>
  <li class="tab-title" role="presentational" ><a href="#panel2-4" role="tab" tabindex="0" aria-selected="false" controls="panel2-4">Tab 4</a></li>
</ul>
<div class="tabs-content">
  <section role="tabpanel" aria-hidden="false" class="content active" id="panel2-1">
    <h2>First panel content goes here...</h2>
  </section>
  <section role="tabpanel" aria-hidden="true" class="content" id="panel2-2">
    <h2>Second panel content goes here...</h2>
  </section>
  <section role="tabpanel" aria-hidden="true" class="content" id="panel2-3">
    <h2>Third panel content goes here...</h2>
  </section>
  <section role="tabpanel" aria-hidden="true" class="content" id="panel2-4">
    <h2>Fourth panel content goes here...</h2>
  </section>
</div>

app/views/profiles/_rsvped_hangouts.html.erb
      <div class="chat-panel box text-center">
        <div class="chat-title">
          <h5><%= hangout.name %></h5>
          <span class="label round secondary"><%= hangout.language.name %></span>
        </div>
        <div class="chat-time">
          <div class="row">
            <div class="large-12 columns">
              <div class="row">
                <% if is_live(hangout.start_time, hangout.end_time) %>
                  <div class="large-2 columns">
                    <span class="label round alert">LIVE</span>
                  </div>
                  <div class="large-6 columns">
                    <p><i class="fi-clock"></i> Ends in <%= time_to_end(hangout.end_time) %></p>
                  </div>                  
                  <% else %>
                  <div class="large-6 columns">
                    <p><%= hangout.start_time.strftime("%b %e, '%y - %I:%M%P") %></p>
                  </div>
                  <div class="large-4 columns">
                  <p><i class="fi-clock"></i> <%= chat_length(hangout.start_time, hangout.end_time) %></p>
                  </div>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="chat-description">
          <%= link_to language_hangout_path(hangout.language, hangout), class: "label round secondary center" do %>
            <i class="fi-link"></i> View
            <% end %>
          <p><%= hangout.description %></p>
          <div class="host">
            <%= link_to( image_tag(hangout.user.avatar.url(:thumb)), profile_path(hangout.user)) %>
            <p><%= link_to hangout.user.username, profile_path(hangout.user) %></p>
            <% if ( user_signed_in? && hangout.user == current_user) || ( user_signed_in? && current_user.admin? ) %>
            <%= link_to edit_language_hangout_path(language, hangout), title: "Edit" do %>
              <span class="left-margin"><i class="fi-pencil"></i></span>
            <% end %>
            <%= link_to language_hangout_path(language, hangout), title: "Delete", method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="left-margin"><i class="fi-x"></i></span>
              </p>
            <% end %>
          <% end %>
          </div>
          <br>
          
        </div>
        <div class="chat-buttons">
          <ul>
            <% if is_live(hangout.start_time, hangout.end_time) %>
            <li class="chat"><%= link_to 'Join', language_hangout_path(language, hangout), class: "chat-button-big" %></li>
            <% elsif is_planned(hangout.start_time) %>
              <li class="chat"><div id="<%= 'rsvp-submit' + hangout.id.to_s %>">
                <%= render partial: 'rsvps/rsvp_hangout', locals: { language: language, hangout: hangout } %>
              </div></li>
            <% else %>
              <li class="chat"><%= link_to 'View', language_hangout_path(language, hangout), class: "chat-button-big" %></li>
            <% end %>
            <li class="chat">
              <div id="<%= 'rsvp-count' + hangout.id.to_s %>">
                <a class="chat-button" href="#" data-reveal-id="chatMembers<%= hangout.id %>"><i class="fi-torsos"></i> <%= rsvp_count(hangout) %></a>
              </div>
            </li>
          </ul>
          
        </div>
      </div>

      <div id="chatMembers<%= hangout.id %>" class="reveal-modal" data-reveal>
        <%= render partial: 'hangouts/chat_members', locals: { hangout: hangout, user: hangout.user } %>
        <a class="close-reveal-modal">&#215;</a>
      </div>

app/views/profiles/_rsvped_tab.html.erb
<!-- RSVPed hangouts -->
		  <div class="content active" id="rsvpedChats">
		    <div class="row">
			  <div id="pins" class="transitions-enabled small-12 medium-10 large-6">
			  	<% unless @user_rsvps.present? %>
			  		<div class="text-center">
			  			<% if current_user == @profile.user %>
			  			<h3>You don't have any scheduled chats.</h3>
			  			<p><%= link_to 'Find some chats', languages_path %> that sound interesting and click 'RSVP'.</p>
			  			<% else %>
			  			<h3><%=@profile.user.username %> isn't planning to attend any chats right now.</h3>
						<% end %>
			  		</div>
			  	<% else %>

				<% @user_rsvps.each do |rsvp| %>
					<% unless is_finished(rsvp.rsvped.end_time) %>
					<%= render partial: 'profiles/rsvped_hangouts', locals: {language: rsvp.rsvped.language.id, hangout: rsvp.rsvped } %>
					<% end %>
				<% end %>
				<% end %>
				</div>
			</div>
		  </div>

app/views/profiles/_tabs.html.erb
<dl class="tabs" data-tab>
  <dd class="active"><a id="numero2" href="#myChats">My Chats</a></dd>
  <dd><a id="numero3" href="#scheduledChats">Upcoming Chats</a></dd>
  <dd><a id="numero4" href="#followingChats">Following Chats</a></dd>
</dl>
<div class="tabs-content">
  <div class="content active" id="myChats">
    <%= render 'profiles/my_chats_tab' %>
  </div>
  <div class="content" id="scheduledChats">
	    <%= render 'profiles/rsvped_tab' %>
  </div>
  <div class="content" id="followingChats">
	    <%= render 'profiles/following_chats_tab' %>
  </div>
</div>

app/views/profiles/_tour.html.erb
<ol class="joyride-list" data-joyride data-options="cookie_monster:true; cookie_name:'joyride'">
  <li data-id="firstStop" data-text="Next" data-options="tip_location: top; prev_button: false">
    <p>Hello and welcome to your profile. Click on 'Settings' to change your username, add a bio, or change your profile picture.</p>
  </li>
  <li data-id="numero1" data-class="custom so-awesome" data-text="Next" data-prev-text="Prev">
    <h4>Follow Users</h4>
    <p>Following people is a great way to get updates of that person's conversations.</p>
  </li>
  <li data-id="numero2" data-button="Next" data-prev-text="Prev" data-options="tip_location:top;tip_animation:fade">
    <h4>My Chats Tab</h4>
    <p>On this tab, you can browse all of the conversations you start or post messages in.</p>
  </li>
  <li data-id="numero3" data-button="Next" data-prev-text="Prev" data-options="tip_location:top;tip_animation:fade">
    <h4>Upcoming Chats Tab</h4>
    <p>When you click 'RSVP' on a future chat, it will show up here.</p>
  </li>
  <li data-id="numero4" data-button="Next" data-prev-text="Prev" data-options="tip_location:top;tip_animation:fade">
    <h4>Following Chats Tab</h4>
    <p>These are chats created by the people you follow.</p>
  </li>
  <li data-id="End" data-button="End" data-prev-text="Prev" data-options="tip_location:top;tip_animation:fade">
    <h4>Follow a Language</h4>
    <p>You can post new conversations easily from your profile if you follow a language. Click 'End' and then follow your first language.</p>
  </li>
</ol>

app/views/profiles/_tour_js.html.erb
<script type="text/javascript">
	$(document).foundation('joyride', 'start');
</script>

app/views/profiles/show.html.erb
<div class="text-center profile-head">
	<% if current_user.admin? %>
	<div class="large-3 panel center"><%= User.all.count %> Users</div><% end %>
	<%= image_tag(@user.avatar.url(:medium)) %>
	<h2><%= @profile.user.username %></h2>
	<p class='user-bio'><%= @profile.user.bio %></p>
	<div class="user-level">
	</div>
	<p class="sub-text"><%= @profile.user.location %></p>
	<a href="#" data-reveal-id="followerModal">Followers <%= @user.followers_by_type_count('User') %></a>, <a id="numero1" href="#" data-reveal-id="followingModal">Following <%= @user.following_by_type_count('User') %></a>
	<br>
	<% if user_signed_in? && current_user == @profile.user %>
	<%= link_to edit_user_registration_path do %>
		<i id="firstStop" class="fi-widget"></i> Settings
	<% end %>
	<% else %>
			<%= render partial: 'follows/user_follow', locals: { user: @profile.user } %>
	<% end %>
</div>

<div class="row">
	<div class="small-12 medium-12 large-12">
		<%= render partial: 'profiles/tabs', locals: {user: @user} %>
	</div>
</div>

<div id="followingModal" class="reveal-modal medium" data-reveal>
	<%= render 'profiles/following' %>
  <a class="close-reveal-modal">&#215;</a>
</div>

</div>

<div id="followerModal" class="reveal-modal medium" data-reveal>
	<%= render 'profiles/followers' %>
  <a class="close-reveal-modal">&#215;</a>
</div>

<%= render 'profiles/tour' %>
<%= render 'profiles/tour_js' %>