config/routes.rb
Chatroom::Application.routes.draw do
  get "about" => "pages#about", as: "about"
  get "contact" => "pages#contact", as: "contact"
  devise_for :users
  resources :profiles, only: [:show]
  resources :languages do
      get "followers" => "languages#languagefollowers", as: "languages_followers"
    resources :hangouts do
      resources :posts, only: [:create]
      get 'tags/:tag', to: 'hangouts#show', as: "tag"
    end
  end

  resources :rsvps, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  resources :languagefollows, only: [:create, :destroy]

  root 'pages#home'

end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :hangouts, dependent: :destroy
	has_many :users, through: :hangouts
	has_many :posts, through: :hangouts
	has_many :rsvps, through: :hangouts
	acts_as_followable
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, except: [:index]
  before_action :check_admin, except: [:index, :languagefollowers]

  # GET /languages
  # GET /languages.json
  def index
    if params[:following].present?
      @languages = current_user.following_by_type('Language')
    else
      @languages = Language.all.order('name ASC')
    end
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to root_path, notice: 'language was successfully created.' }
        format.json { render action: 'show', status: :created, location: @language }
      else
        format.html { render action: 'new' }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'language was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url }
      format.json { head :no_content }
    end
  end

  def languagefollowers
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id]) rescue Language.find(params[:language_id])
    end

    def check_admin
      unless user_signed_in? && current_user.admin?
        redirect_to root_path, alert: "Sorry, you can't do that."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:name)
    end
end

app/helpers/languages_helper.rb
module LanguagesHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def scheduled_hangout_count(language)
  	Hangout.where(["language_id = ? and private = ? and start_time > ?", language.id, false, Time.now]).count
  end

  def live_hangout_count(language)
  	Hangout.where(["language_id = ? and private = ? and start_time <= ? and end_time > ?", language.id, false, Time.now, Time.now]).count
  end
end

app/views/languages/_follow_language.html.erb
<h3><% unless current_user.following?(language) %>
    <%= link_to languagefollows_path(id: language), remote: true, method: :post, id:"follow-submit", class: "follow-star", title: 'Follow' do %>
        <i class="fi-star"></i>
    <% end %>
<% else %>
    <%= link_to languagefollow_path(id: language), remote: true, method: :delete, class: "following-star", title: 'Following' do %>
        <i class="fi-star"></i>
    <% end %>
<% end %> <%= language.name %></h3>

app/views/languages/_form.html.erb
<div class="row panel small-12 medium-10 large-6">
    <%= form_for(@language) do |f| %>
      <% if @language.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@language.errors.count, "error") %> prohibited this language from being saved:</h2>

          <ul>
          <% @language.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.text_field :name, placeholder: "Enter a new language" %>
      </div>

      <div class="actions">
        <%= f.submit class: "button success" %>
      </div>
    <% end %>
</div>

app/views/languages/_language_followers.html.erb
<div id="followersModal<%=language.id%>" class="reveal-modal language-followers" data-reveal>
	<div class="followers text-center row">
	<div class="large-12">
		<h4>People Following <%= language.name %></h4>
	      <% if language.followers_by_type_count('User') == 0 %>
		  <p>Cool! You can be this language's first follower! <%= link_to 'Follow', follows_path(id: @profile), method: :post, id:"follow-submit", class: "button small success round tiny" %></p>
			<% else %>
			<table>
				<tbody>
				  <% language.user_followers.each do |user| %>
				    <% unless current_user == user %>
				      <tr>
						<td><%= link_to( image_tag(user.avatar.url(:thumb)), profile_path(user.profile)) %></td>
						<td>
							<%= link_to user.username, profile_path(user.profile), class: "follower-name" %>
							<p class="follower-bio"><%= truncate(user.bio, :length => 60) %></p>
						</td>
						<td>
						<div id="<%= user.username %>-follow">
							<%= render partial: 'follows/user_follow', locals: { profile: user.profile} %>
						</div>
					    </td>
					  </tr>
					<% end %>
				  <% end %>
				  </tbody>
			</table>
		  <% end %>
    	<a class="close-reveal-modal">&#215;</a>
	</div>
   </div>
</div>

app/views/languages/index.html.erb
<% unless user_signed_in? %>
<%= render 'layouts/welcome' %>
<% else %>
  <div class="small-12 medium-12 large-12 columns text-center">

    <h1>Choose a Language</h1>
    
    <p>Browse languages below or click the <i class="fi-star"></i> to get updates about those languages.</p>
    <button href="#" data-dropdown="sort" aria-controls="drop1" aria-expanded="false" class="button dropdown tiny round">Sort</button><br>
          <ul id="sort" data-dropdown-content class="f-dropdown" aria-hidden="true" tabindex="-1">
            <li><%= link_to 'All', languages_path %></li>
            <li><%= link_to 'Following', languages_path(:following=> true) %></li>
          </ul>
    <%if user_signed_in? && current_user.admin? %><%= link_to 'New Language', new_language_path, class: "button small round success" %><% end %>
  </div>

    <div class="row">
      <div id="pins" class="transitions-enabled small-12 medium-12 large-12">
        <% @languages.each do |language| %>
        <div class="box language-panel text-center">
          <div id="follow-language<%= language.name %>"><%= render partial: 'languagefollows/follow_language', locals: {language: language} %></div>
          <div class="row">
            <p class="language"><%= link_to language_languages_followers_path(language_id: language) do %>
              <i class="fi-torsos-all"></i> <span id="<%= language.name %>-follows"><%= language.followers_count %> Follower<%= if language.followers_count  > 1 || language.followers_count == 0 then "s" end %></span></a>
              <% end %></p>
            
          </div>
          <div class="row">
            <p class="language"><%= link_to language_hangouts_path(language, :scheduled => true) do %>
              <i class="fi-calendar"></i> <%= scheduled_hangout_count(language) %> Future Chat<%= if scheduled_hangout_count(language) > 1 || scheduled_hangout_count(language) == 0 then "s" end %>
              <% end %></p>
          </div>
          <div class="row">
            <p class="language"><%= link_to language_hangouts_path(language, :live => true) do %>
              <i class="fi-play"></i> <%= live_hangout_count(language) %> Live Chat<%= if live_hangout_count(language) > 1 || live_hangout_count(language) == 0 then "s" end %>
              <% end %></p>
          </div>
          <br>
          
          <div class="language-buttons">
            <%= link_to 'Browse', language_hangouts_path(language), class: "language-button" %>
          </div>
        </div>

        <% end %>
      
      </div>
    </div>
  <% end %>

app/views/languages/languagefollowers.html.erb
	<div class="text-center row">
	<div class="large-12">
		<h4>People Following <%= @language.name %></h4>
	      <% if @language.followers_by_type_count('User') == 0 %>
		  <p>No one is following <%= @language.name %> yet. Why not be the first one?</p>
			<% else %>
				<% @language.user_followers.each do |user| %>
				<div class="user-panel-container">
					<div class="user-panel">
				      <div class="clearfix"><%= link_to( image_tag(user.avatar.url(:medium)), profile_path(user.profile), title: "View Profile") %></div>
					  <%= link_to user.username, profile_path(user.profile), class: "follower-name" %><br>
					  <p class="follower-bio"><%= truncate(user.bio, :length => 60) %></p>
					  <p class="follower-bio sub-text">Joined in <%= user.created_at.strftime('%B %Y') %></p>
					  <p class="sub-text"><% unless !user.location.present? %><i class="fi-marker"></i> <%= user.location %></p><% end%>

					  <p class="sub-text">
					  	Followers <%= user.followers_by_type_count('User') %>, Following <%= user.following_by_type_count('User') %>
					  </p>

					  <%= render partial: 'follows/user_follow', locals: { user: user } %>
					</div>
				</div>
				<% end %>
		  <% end %>
	</div>
   </div>

app/views/languages/new.html.erb
<h1>New Language</h1>

<%= render partial: 'form', locals: {language: @language} %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @language.name %>
</p>
<%= link_to 'New Hangout', new_language_hangout_path(@language, @hangout) %>

<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>