config/routes.rb
Chatroom::Application.routes.draw do
  get "about" => "pages#about", as: "about"
  get "contact" => "pages#contact", as: "contact"
  devise_for :users
  resources :profiles, only: [:show]
  resources :languages do
      get "followers" => "languages#languagefollowers", as: "languages_followers"
    resources :hangouts do
      resources :posts, only: [:create]
      get 'tags/:tag', to: 'hangouts#show', as: "tag"
    end
  end

  resources :rsvps, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  resources :languagefollows, only: [:create, :destroy]

  root 'pages#home'

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :user
  belongs_to :rsvped, polymorphic: true
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
	before_action :set_hangout
	before_action :authenticate_user!

	def create
		Rsvp.create(rsvped: @hangout, user: current_user)
		render :create
	end

	def destroy
		Rsvp.where(rsvped_id: @hangout.id, user_id: current_user.id).first.destroy
		render :create
	end

	private

	def set_hangout
    	@hangout = Hangout.find(params[:hangout_id]) rescue Hangout.find(params[:id])
  	end
end

app/views/rsvps/_rsvp_hangout.html.erb
<div class="rsvp">
	<%- unless current_user.rsvped_hangouts.exists?(id: hangout.id) -%>
	<%= link_to 'RSVP', rsvps_path(hangout_id: hangout), remote: true, method: :post, :id => 'rsvp-submit' + hangout.id.to_s, class: 'chat-button-big' %>
	<%- else -%>
	<%= link_to rsvp_path(hangout), remote: true, method: :delete, class: 'chat-button-big-inverse' do %>
		<i class="fi-check"></i> 
		<% end %>
	<%- end -%>
</div>

app/views/rsvps/create.js.erb
$('#rsvp-submit<%= @hangout.id.to_s %>').html('<%= escape_javascript( render partial: 'rsvps/rsvp_hangout', locals: { hangout: @hangout }  ) %>');
$('#rsvp-count<%= @hangout.id.to_s %> a.chat-button').html('<i class="fi-torsos"> </i><%= j rsvp_count(@hangout).to_s %>');