config/routes.rb
Chatroom::Application.routes.draw do
  get "about" => "pages#about", as: "about"
  get "contact" => "pages#contact", as: "contact"
  devise_for :users
  resources :profiles, only: [:show]
  resources :languages do
      get "followers" => "languages#languagefollowers", as: "languages_followers"
    resources :hangouts do
      resources :posts, only: [:create]
      get 'tags/:tag', to: 'hangouts#show', as: "tag"
    end
  end

  resources :rsvps, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  resources :languagefollows, only: [:create, :destroy]

  root 'pages#home'

end

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-34642215-4', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_home_menu.html.erb
<nav class="top-bar foundation-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">fluentli conversations</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if user_signed_in? %>
        <li><%= link_to 'Find a Conversation', languages_path %></li>
        <li><%= link_to 'Have an idea?', contact_path %></a></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path , method: 'delete' %></li>
        <li><%= link_to 'Profile', edit_user_registration_path %></li>
      <% else %>
        <li><%= link_to 'About', about_path %></a></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/_menu.html.erb
<nav class="top-bar foundation-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">fluentli conversations</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      
      <% if user_signed_in? %>
        <li><%= link_to 'Find a Conversation', languages_path %></li>
        <li><%= link_to 'Have an idea?', contact_path %></a></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path , method: 'delete' %></li>
        <li><%= link_to 'Profile', profile_path(current_user.profile) %></li>
      <% else %>
        <li><%= link_to 'About', about_path %></a></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box text-center <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_welcome.html.erb
<div class="hero">
	<%= render 'layouts/home_menu' %>
	<div class="focus-area small-12 medium-12 large-12 columns">
		<h1>Join Conversations in Any Language</h1>
		<p class="lead big-bottom">A <span class="highlight">friendly</span> place to use the language you're learning.</p>
		<div class="row">
			<div class="small-12 medium-12 large-12 columns">
				<a href="#" data-reveal-id="signupModal" class="button success large">Sign Up</a>
				<a href="#" data-reveal-id="signinModal" class="button secondary large">Sign In</a>
			</div>
		</div>
	</div>

		<div id="signupModal" class="reveal-modal small" data-reveal>
	  		<%= render 'devise/shared/registration' %>
	  		<a class="close-reveal-modal">&#215;</a>
		</div>

		<div id="signinModal" class="reveal-modal small" data-reveal>
	  		<%= render 'devise/shared/sign_in' %>
	  		<a class="close-reveal-modal">&#215;</a>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "fluentli conversations - Chat for Language Learners" %></title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <script src="//load.sumome.com/" data-sumo-site-id="48cd5e959444a9481e1023e2fd6737309d68b6eec30f06bf3d929b8808b54e96" async></script>
  </head>

  <body>
    <%= render 'layouts/messages' %>

    <% unless current_page?(root_path) %>
    <%= render 'layouts/menu' %>
    <% end %>

    <%= yield %>
  </body>
</html>